// Données d'exemple — à remplacer par le vrai contenu du dictionnaire.
// Structure : word, definition, example (optionnel), category (optionnel).
const List<Map<String, dynamic>> sampleData = [
  {
    'word': 'Abonder',
    'definition': 'Être en grande quantité, exister en abondance.',
    'example': 'Les fruits abondent dans cette région en été.',
    'category': 'Verbe',
    'is_favorite': 0,
  },
  {
    'word': 'Abstrait',
    'definition': 'Qui relève de l\'abstraction, sans référence à un objet concret.',
    'example': 'L\'art abstrait ne représente pas la réalité de façon littérale.',
    'category': 'Adjectif',
    'is_favorite': 0,
  },
  {
    'word': 'Acuité',
    'definition': 'Caractère de ce qui est aigu, intense ou précis.',
    'example': 'L\'acuité visuelle de cet aigle est remarquable.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Adage',
    'definition': 'Courte sentence populaire exprimant une vérité d\'expérience.',
    'example': 'L\'adage dit : « pierre qui roule n\'amasse pas mousse ».',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Affable',
    'definition': 'Qui accueille avec douceur et bienveillance, d\'une politesse agréable.',
    'example': 'Cette hôtesse est affable avec tous les visiteurs.',
    'category': 'Adjectif',
    'is_favorite': 0,
  },
  {
    'word': 'Alléger',
    'definition': 'Rendre moins lourd, diminuer le poids ou la charge.',
    'example': 'Il faudra alléger le sac avant la randonnée.',
    'category': 'Verbe',
    'is_favorite': 0,
  },
  {
    'word': 'Ambiguïté',
    'definition': 'Caractère de ce qui peut être interprété de plusieurs façons.',
    'example': 'Son message est plein d\'ambiguïté.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Apaiser',
    'definition': 'Calmer, rendre moins violent ou moins douloureux.',
    'example': 'Ce médicament apaise la douleur rapidement.',
    'category': 'Verbe',
    'is_favorite': 0,
  },
  {
    'word': 'Ardeur',
    'definition': 'Énergie vive et enthousiaste dans l\'action ou le sentiment.',
    'example': 'Elle travaille avec ardeur pour réussir.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Aspiration',
    'definition': 'Désir profond, ambition ou idéal vers lequel on tend.',
    'example': 'Son aspiration est de devenir médecin.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Bénévole',
    'definition': 'Qui agit sans rémunération, par engagement volontaire.',
    'example': 'Il est bénévole dans une association humanitaire.',
    'category': 'Adjectif / Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Bienveillance',
    'definition': 'Disposition favorable envers quelqu\'un, bonté attentionnée.',
    'example': 'L\'enseignant traite ses élèves avec bienveillance.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Bravoure',
    'definition': 'Qualité de celui qui fait preuve de courage face au danger.',
    'example': 'Sa bravoure lors de l\'incendie a sauvé plusieurs vies.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Candeur',
    'definition': 'Pureté d\'âme naïve et sincère, innocence.',
    'example': 'La candeur de cet enfant est touchante.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Clairvoyance',
    'definition': 'Faculté de voir clairement et justement les choses.',
    'example': 'Sa clairvoyance lui a permis d\'éviter l\'erreur.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Cohérence',
    'definition': 'Rapport logique et harmonieux entre les parties d\'un ensemble.',
    'example': 'La cohérence de son raisonnement est irréprochable.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Conviction',
    'definition': 'Certitude ferme qu\'on a de quelque chose, croyance profonde.',
    'example': 'Il défend ses idées avec conviction.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Délibérer',
    'definition': 'Réfléchir, examiner une question avant de prendre une décision.',
    'example': 'Le jury a délibéré pendant deux heures.',
    'category': 'Verbe',
    'is_favorite': 0,
  },
  {
    'word': 'Dénuement',
    'definition': 'État de manque extrême, grande pauvreté.',
    'example': 'Cette famille vit dans le dénuement total.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Discernement',
    'definition': 'Capacité à juger clairement, à distinguer le vrai du faux.',
    'example': 'Choisir ses amis demande du discernement.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Éclore',
    'definition': 'S\'ouvrir, apparaître, naître ou se développer.',
    'example': 'Les fleurs ont éclos au printemps.',
    'category': 'Verbe',
    'is_favorite': 0,
  },
  {
    'word': 'Éloquence',
    'definition': 'Art de bien parler, de convaincre par la parole.',
    'example': 'Son éloquence a captivé tout l\'auditoire.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Empathie',
    'definition': 'Capacité à comprendre et partager les sentiments d\'autrui.',
    'example': 'Un bon médecin fait preuve d\'empathie envers ses patients.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Épanouissement',
    'definition': 'Développement complet et harmonieux d\'une personne ou d\'une chose.',
    'example': 'L\'école doit favoriser l\'épanouissement de chaque élève.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Équanimité',
    'definition': 'Calme d\'âme, égalité d\'humeur face aux événements.',
    'example': 'Il a accueilli la nouvelle avec équanimité.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Ferveur',
    'definition': 'Ardeur intense dans les sentiments, notamment religieux ou passionnés.',
    'example': 'Les fidèles priaient avec ferveur.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Flamboyant',
    'definition': 'Qui brille avec éclat, très vif et remarquable.',
    'example': 'Son discours flamboyant a enflammé la foule.',
    'category': 'Adjectif',
    'is_favorite': 0,
  },
  {
    'word': 'Frugalité',
    'definition': 'Caractère de ce qui est simple et sobre, sans excès.',
    'example': 'La frugalité de son repas contrastait avec l\'abondance ambiante.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Gratitude',
    'definition': 'Sentiment de reconnaissance envers quelqu\'un.',
    'example': 'Elle lui a exprimé sa gratitude pour son aide.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Hardiesse',
    'definition': 'Audace, courage qui ose aller au-delà des limites ordinaires.',
    'example': 'Escalader cette falaise demande une grande hardiesse.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Humilité',
    'definition': 'Vertu qui consiste à se connaître sans orgueil excessif.',
    'example': 'Il a accepté la critique avec humilité.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Immuable',
    'definition': 'Qui ne change pas, qui reste constant.',
    'example': 'Les lois de la nature sont immuables.',
    'category': 'Adjectif',
    'is_favorite': 0,
  },
  {
    'word': 'Indolence',
    'definition': 'Disposition à éviter l\'effort, paresse nonchalante.',
    'example': 'Son indolence l\'empêche d\'avancer dans ses projets.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Ingéniosité',
    'definition': 'Qualité d\'un esprit inventif capable de trouver des solutions originales.',
    'example': 'Son ingéniosité lui a permis de réparer l\'appareil avec peu de moyens.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Intégrité',
    'definition': 'Qualité d\'une personne honnête et droite, irréprochable sur le plan moral.',
    'example': 'L\'intégrité de ce juge est reconnue de tous.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Jubilation',
    'definition': 'Joie vive et expansive, allégresse débordante.',
    'example': 'La victoire de l\'équipe a provoqué une jubilation générale.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Judicieux',
    'definition': 'Qui manifeste un bon jugement, sensé et avisé.',
    'example': 'C\'est un choix judicieux dans cette situation.',
    'category': 'Adjectif',
    'is_favorite': 0,
  },
  {
    'word': 'Lucidité',
    'definition': 'Clarté de l\'esprit, aptitude à voir et à comprendre les choses telles qu\'elles sont.',
    'example': 'Avec lucidité, elle a analysé ses erreurs.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Magnanimité',
    'definition': 'Grandeur d\'âme qui pousse à pardonner et à s\'élever au-dessus des petitesses.',
    'example': 'Le vainqueur a fait preuve de magnanimité envers ses adversaires.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Méticuleuse',
    'definition': 'Qui prête attention aux moindres détails, très soigneux.',
    'example': 'Son travail méticuleuse ne laisse aucune place à l\'erreur.',
    'category': 'Adjectif',
    'is_favorite': 0,
  },
  {
    'word': 'Modération',
    'definition': 'Comportement qui évite les excès, mesure et retenue.',
    'example': 'Boire de l\'alcool avec modération est conseillé.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Nonchalance',
    'definition': 'Manque de zèle, comportement décontracté et sans effort apparent.',
    'example': 'Il répondit avec nonchalance sans lever les yeux.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Obstination',
    'definition': 'Attachement tenace à une idée ou un comportement malgré les obstacles.',
    'example': 'Son obstination lui a finalement permis de réussir.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Opportun',
    'definition': 'Qui vient à propos, au bon moment.',
    'example': 'Sa remarque était opportune dans ce débat.',
    'category': 'Adjectif',
    'is_favorite': 0,
  },
  {
    'word': 'Parcimonie',
    'definition': 'Épargne excessive, habitude de dépenser le moins possible.',
    'example': 'Il gère ses ressources avec parcimonie.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Perspicace',
    'definition': 'Capable de comprendre rapidement et avec finesse.',
    'example': 'Un observateur perspicace remarquera les détails.',
    'category': 'Adjectif',
    'is_favorite': 0,
  },
  {
    'word': 'Prérogative',
    'definition': 'Avantage ou privilège exclusif attaché à une fonction ou un titre.',
    'example': 'C\'est une prérogative du président de signer les décrets.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Probité',
    'definition': 'Honnêteté scrupuleuse, droiture morale.',
    'example': 'La probité de ce fonctionnaire est exemplaire.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Prudence',
    'definition': 'Vertu qui consiste à éviter les risques inutiles par réflexion préalable.',
    'example': 'La prudence s\'impose sur cette route verglacée.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Réciprocité',
    'definition': 'Caractère de ce qui est mutuel, échange équitable entre deux parties.',
    'example': 'La réciprocité est essentielle dans une amitié vraie.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Résilience',
    'definition': 'Capacité à surmonter les épreuves et à se reconstruire.',
    'example': 'Après la crise, la résilience de cette communauté est admirable.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Sagacité',
    'definition': 'Pénétration d\'esprit, finesse de jugement.',
    'example': 'La sagacité de ce détective lui a permis de résoudre l\'affaire.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Sérénité',
    'definition': 'État d\'esprit calme et paisible, tranquillité d\'âme.',
    'example': 'Elle affronte les difficultés avec sérénité.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Sobriété',
    'definition': 'Caractère tempéré, modéré dans la consommation ou l\'expression.',
    'example': 'La sobriété de sa tenue vestimentaire est élégante.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Solidarité',
    'definition': 'Sentiment d\'appartenance commune qui pousse à s\'entraider.',
    'example': 'La solidarité entre voisins est précieuse en temps de crise.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Stoïque',
    'definition': 'Qui supporte les douleurs ou les épreuves sans se plaindre.',
    'example': 'Il a reçu la mauvaise nouvelle de façon stoïque.',
    'category': 'Adjectif',
    'is_favorite': 0,
  },
  {
    'word': 'Subtilité',
    'definition': 'Caractère fin et délicat, nuance difficile à saisir.',
    'example': 'La subtilité de son humour échappe à beaucoup.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Ténacité',
    'definition': 'Qualité de celui qui s\'attache fermement à ses objectifs malgré les obstacles.',
    'example': 'C\'est grâce à sa ténacité qu\'il a réussi.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Tolérance',
    'definition': 'Respect des opinions et comportements différents des siens.',
    'example': 'La tolérance est fondamentale dans une société diverse.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Transcender',
    'definition': 'Dépasser, aller au-delà des limites ordinaires.',
    'example': 'L\'artiste cherche à transcender les conventions.',
    'category': 'Verbe',
    'is_favorite': 0,
  },
  {
    'word': 'Urbanité',
    'definition': 'Politesse raffinée, courtoisie propre à la vie en société.',
    'example': 'Il reçoit ses invités avec beaucoup d\'urbanité.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Véracité',
    'definition': 'Qualité de ce qui est vrai, conformité à la réalité.',
    'example': 'La véracité de ses propos a été confirmée.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Vigilance',
    'definition': 'Attention soutenue, état d\'éveil pour surveiller ou prévenir.',
    'example': 'La vigilance des pompiers a évité un incendie majeur.',
    'category': 'Nom',
    'is_favorite': 0,
  },
  {
    'word': 'Zèle',
    'definition': 'Ardeur à accomplir un devoir, dévouement enthousiaste.',
    'example': 'Il accomplit ses tâches avec zèle.',
    'category': 'Nom',
    'is_favorite': 0,
  },
];
